### ISSUE TITLE
Add some docs to configure using the fork with Gradle

### ISSUE THREAD

**Issue by stephanenicolas** [facebook/proguard#7]
Up to now, the only way I could find to use this fork instead of stock proguard when using gradle is to replace the proguard jar inside gradle's cache. 

But I am sure there is a cleaner way. Can you publish some instructions to using this fork with gradle ?

**Comment by vipinhelloindia** [comment]
+1

**Comment by niedzielski** [comment]
The example[0] seems to work for me (I just used the buildscript bit at the top) although I didn't recognize any performance improvements in my test app. In a previous project, we used Ant with this fork and it was quite obvious.

[0] https://github.com/facebook/proguard/blob/master/examples/gradle/android.gradle

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by alsutton** [comment]
Closing due to @niedzielski offering a solution.

**Comment by niedzielski** [comment]
@alsutton, my bad. I wrote that response hastily and never followed up. I don't think the solution referenced worked at all since I can't tell the difference between it being enabled or not. Please reopen this issue :)

**Comment by alsutton** [comment]
I'm going to close this issue as a wontfix because any instructions added here for a specific build system could easily become out of sync with updates to the build tool. If you need instructions for integrating with a specific build tool please open an issue with the authors of the build tool who can ensure that the instructions are kept up to date with new releases of that tool
